spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306?lianxi7
    username: root
    password: root
  redis:
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        max-active: 8
        min-idle: 0
mybatis:
  type-aliases-package: com.example.lianxi7
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
